name: Bug report
description: Report something that isn't working
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Commands or steps to trigger the bug.
      placeholder: |
        1. dodgylegally run --count 5
        2. ...

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `dodgylegally --version` or `pip show dodgylegally`.
      placeholder: "0.1.0"

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Linux
        - Windows
        - Other
